apiVersion: v1
kind: Service
metadata:
  name: {{ include "bucktooth.fullname" . }}
  labels:
    {{- include "bucktooth.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.wsPort }}
      targetPort: ws
      protocol: TCP
      name: ws
  selector:
    {{- include "bucktooth.selectorLabels" . | nindent 4 }}
